name: Build Docker Image & Publish Dashboard

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: gtmnerr # CHANGE THIS TO BE A SECRET ON GITHUB ###
          password: dckr_pat__hEdxbRrtLePYXseurTdnZ7da6M # CHANGE THIS TO BE A SECRET ON GITHUB ###

      # Build and push the Docker image to dockerhub    
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./05_DASHBOARD/Dockerfile
          push: true
          tags: gtmnerr/dashboard:latest
        
      # run the docker image to publish to shinyapps.io 
      - name: Run docker image
        # CHANGE ALL VARIABLES TO BE SECRETS ON GITHUB ###
        run: >
          docker run -e SHINY_ACC_NAME=gtmnerr \
          -e TOKEN=C45D396CDEDC0F87E0415BDDCB10D264 \
          -e SECRET=amOf/66XsI1PtjFXGhEmWaBcuIzlhY6WLBirWL2y \
          gtmnerr/dashboard:latest