name: Build and Push Docker Image

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

# Uncoimment this to also push to dockerhub
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./05_DASHBOARD/Dockerfile
      #     push: true
      #     tags: your_dockerhub_username/your_repository:${{ github.ref_name }}-${{ steps.date.outputs.date }}-${{ github.sha }}
      #     # This tag includes the branch name, the current date, and the commit SHA

      # run the docker image supply the secrets from the github secrets store.  
      - name: execute
        run: >
          docker run 
          -e SHINY_ACC_NAME=${{"christophermarais"}} 
          -e TOKEN=${{"908D29B518B4A47C935C6E63B03D4C73"}} 
          -e SECRET=${{"cH2hwZOTvRMKm5ouNDaX6zJrDo0WVVVsvOTzKRqu"}} 
          main   
